version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_login
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./source/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./docker
    volumes:
      - ./source/hacker-login-form/src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

