version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:80"
    volumes:
      - ./src:/var/www/html
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./src/database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  db_data:
