version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lab_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
